apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: dev-
namespace: dev-mockten

images:
- name: mockten/adder
  # newname: gcr.io/_GCP_PROJECT_ID_/mockten/adder
  newname: gcr.io/planar-courage-414205/mockten/adder
  newTag: latest
replicas:
- name: deploy
  count: 2

resources:
- ../../../base/adder

patches:
- path: deploy-patch.yaml
  target:
    group: apps
    version: v1
    kind: Deployment
    name: deploy
- path: secret-patch.yaml
  target:
    version: v1
    kind: Secret
    name: secret