apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy
spec:
  selector:
    matchLabels:
      app: ecfront
  template:
    metadata:
      labels:
        app: ecfront
    spec:
      containers:
      - name: ecfront
        image: mockten/ecfront2
        ports:
          - containerPort: 80
            name: main
        readinessProbe:
          httpGet:
            path: /
            port: 80
          failureThreshold: 3
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 3