apiVersion: v1
kind: Service
metadata:
  name: service
spec:
  selector:
    app: adder
  ports:
    - protocol: TCP
      name: app
      port: 50051
      targetPort: 50051
    - protocol: TCP
      name: prometheus
      port: 9100
      targetPort: 9100
