apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  template:
    spec:
      volumes:
        - name: mysql-persistent-storage
          gcePersistentDisk:
            pdName: dev-mysql-disk
            fsType: ext4

