apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev-mockten
namePrefix: dev-

images:
- name: statefulset
  newTag: "5.6"
replicas:
- name: statefulset
  count: 1

resources:
- ../../../base/mysql
- mysql-pv.yaml
- mysql-pvc.yaml

patches:
- path: statefulset-patch.yaml
  target:
    group: apps
    version: v1
    kind: StatefulSet
    name: statefulset