apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev-mockten
namePrefix: dev-

images:
- name: deploy
  newTag: "5.6"
replicas:
- name: deploy
  count: 1

resources:
- ../../../base/mysql

patches:
- path: deploy-patch.yaml
  target:
    group: apps
    version: v1
    kind: Deployment
    name: deploy