apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev-mockten
namePrefix: dev-

images:
- name: mysql
  newTag: latest
replicas:
- name: statefulset
  count: 2

resources:
- ../../../base/mysql

patches:
- path: statefulset-patch.yaml
  target:
    group: apps
    version: v1
    kind: StatefulSet
    name: statefulset
- path: secret-patch.yaml
  target:
    kind: Secret
    name: mysql-secret