apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  db_host: ZGV2LW15c3FsLXN2Yy5kZXYtbW9ja3Rlbi5zdmMuY2x1c3Rlci5sb2NhbAo=
  db_user: cm9vdA==
  db_pass: S3lQMHJ0RzAh
  db_table: bW9ja3Rlbg==