apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  volumeClaimTemplates:
  - metadata:
      name: dev-mockten-mysql-pvc
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 10Gi