apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: prod-
namespace: production
images:
- name: gcr.io/go-portforio/consumer-test
  newTag: circle-ci
replicas:
- name: payexecution
  count: 1

generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
- name: payexecute-cm
  envs:
  - config/payexe.env

resources:
- ../../../base/payexecution

patches:
- path: deploy-patch.yaml
  target:
    kind: Deployment
    name: payexecution