apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy
spec:
  template:
    spec:
      containers:
        - image: docker.elastic.co/logstash/logstash:8.11.0
          name: logstash
          env:
            - name: REMOTE_DB_HOST
              valueFrom:
                secretKeyRef:
                  name: common-secret
                  key: db_host
            - name: REMOTE_DM_VIEWER_PW
              valueFrom:
                secretKeyRef:
                  name: common-secret
                  key: db_product_viewer_pass
          volumeMounts:
          - name: privatekey-volume
            mountPath: /usr/share/logstash/run/privatekey.json
            subPath: privatekey.json
          resources:
            limits:
              cpu: 2000m
              memory: 2000m
            requests:
              cpu: 100m
              memory: 100m
          command: ["/bin/sh", "-c"]
          args: ["/usr/share/logstash/run.sh"]
      volumes:
      - name: privatekey-volume
        secret:
          secretName: logstash-secret
        