apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy
spec:
  selector:
    matchLabels:
      app: ecfront
  template:
    metadata:
      labels:
        app: ecfront
    spec:
      containers:
      - name: ecfront
        resources:
          limits:
            cpu: 500m
            memory: 500m
          requests:
            cpu: 100m
            memory: 100m
        volumeMounts:
        - name: config-volume
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
          readOnly: true
      volumes:
      - name: config-volume
        configMap:
          name: ecfront-nginx-conf
          items:
          - key: nginx.conf
            path: nginx.conf