apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: dev-
namespace: dev-mockten
images:
- name: gcr.io/go-portforio/ecfront2
  newname: gcr.io/_GCP_PROJECT_ID_/ecfront2
  newTag: latest
replicas:
- name: deploy
  count: 2

resources:
- ../../../base/ecfront

generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
- name: ecfront-cm
  envs:
  - config/ecfront.env

patches:
- path: ingress-patch.yaml
  target:
    kind: Ingress
    name: ingress
# - path: service-patch.yaml
#   target:
#     kind: Service
#     name: svc
- path: deploy-patch.yaml
  target:
    group: apps
    version: v1
    kind: Deployment
    name: deploy