apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: dev-
namespace: dev-mockten
images:
- name: gcr.io/go-portforio/ecfront
  newname: gcr.io/secret-node-394015/ecfront
  newTag: v0.0.1
replicas:
- name: deploy
  count: 1

resources:
- ../../../base/ecfront
- pv.yaml
- pvc.yaml

generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
- name: ecfront-cm
  envs:
  - config/ecfront.env

patches:
- path: ingress-patch.yaml
  target:
    kind: Ingress
    name: ingress
- path: service-patch.yaml
  target:
    kind: Service
    name: svc
- path: deploy-patch.yaml
  target:
    group: apps
    version: v1
    kind: Deployment
    name: deploy