apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: dev-
namespace: dev-mockten
images:
- name: mockten/ecfront2
  newname: gcr.io/_GCP_PROJECT_ID_/mockten/ecfront
  newTag: latest
replicas:
- name: deploy
  count: 2

resources:
- ../../../base/ecfront

patches:
- path: ingress-patch.yaml
  target:
    kind: Ingress
    name: ingress
- path: deploy-patch.yaml
  target:
    group: apps
    version: v1
    kind: Deployment
    name: deploy