apiVersion: v1
kind: PersistentVolume
metadata:
  name: ecfront-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: dev-static-file-disk
    fsType: ext4