apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: prod-
namespace: production
images:
- name: gcr.io/go-portforio/ranking
  newTag: circle-ci
replicas:
- name: ranking
  count: 1

resources:
- ../../../base/ranking
- secret.yaml

#patches:
#- path: payexecute-deploy.yaml
#  target:
#    kind: Deployment
#    name: consumer