apiVersion: v1
kind: Service
metadata:
  name: service
spec:
  selector:
    app: ecpay
  ports:
    - protocol: TCP
      name: app
      port: 50052
      targetPort: 50052
    - protocol: TCP
      name: nodeexporter
      port: 9100
      targetPort: 9100
