apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy
spec:
  selector:
    matchLabels:
      app: ecpay
  template:
    metadata:
      labels:
        app: ecpay
    spec:
      containers:
      - name: ecpay
        image: mockten/ecpay
        env:
          - name: SecretKeyString
            valueFrom:
              secretKeyRef:
                name: ecpay-secret
                key: secret_key_string            
          - name: RedisHost
            valueFrom:
              secretKeyRef:
                name: common-secret
                key: redis_host_with_port
          - name: MysqlIp
            valueFrom:
              secretKeyRef:
                name: common-secret
                key: db_host
          - name: MysqlDB
            valueFrom:
              secretKeyRef:
                name: common-secret
                key: db_table
          - name: MysqlPassword
            valueFrom:
              secretKeyRef:
                name: common-secret
                key: db_pass
          - name: MysqlUser
            valueFrom:
              secretKeyRef:
                name: common-secret
                key: db_user
          - name: DbHost
            valueFrom:
              configMapKeyRef:
                name: ecpay-cm
                key: DbHost
        ports:
        - containerPort: 50052
          name: app
        - containerPort: 9100
          name: prometheus
        resources:
          limits:
            cpu: 200m
            memory: 200m
          requests:
            cpu: 100m
            memory: 100m