apiVersion: batch/v1
kind: Job
metadata:
  name: initial-mockten-job
spec:
  template:
    spec:
      containers:
      - name: copy-init-files
        image: gcr.io/go-portforio/static-file
        command: ["/bin/sh", "-c", "/work/run.sh"]
        args: ["_GDRIVE_URL_"]
        volumeMounts:
        - name: mockten-static-disk
          mountPath: "/mnt/disk"
      restartPolicy: Never
      volumes:
      - name: mockten-static-disk
        persistentVolumeClaim:
          claimName:  ecfront-pvc