apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: production
images:
- name: redis
  newTag: "6.2"
replicas:
- name: redis
  count: 1

resources:
- ../../../base/redis

patches:
- path: deploy-patch.yaml
  target:
    group: apps
    version: v1
    kind: Deployment
    name: redis