apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev-mockten
namePrefix: dev-

images:
- name: mongo
  newname: gcr.io/_GCP_PROJECT_ID_/mockten/mongodb
  newTag: latest
replicas:
- name: statefulset
  count: 2

resources:
- ../../../base/mongodb

patches:
- path: stateful-patch.yaml
  target:
    group: apps
    version: v1
    kind: StatefulSet
    name: statefulset
- path: secret-patch.yaml
  target:
    kind: Secret
    name: secret