apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev-mockten
namePrefix: dev-

images:
- name: mongodb
  newTag: "latest"
replicas:
- name: deploy
  count: 1

resources:
- ../../../base/mongodb

patches:
- path: deploy-patch.yaml
  target:
    group: apps
    version: v1
    kind: Deployment
    name: deploy
- path: secret-patch.yaml
  target:
    kind: Secret
    name: secret
- path: init-config-patch.yaml
  target:
    kind: ConfigMap
    name: init-config