apiVersion: v1
kind: Service
metadata:
  name: svc
spec:
  selector:
    app: ranking
  ports:
    - protocol: TCP
      name: app
      port: 50053
      targetPort: 50053
    - protocol: TCP
      name: nodeexporter
      port: 9100
      targetPort: 9100
