apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: dev-
namespace: dev-mockten

resources:
- ../../../base/common

patches:
- path: secret-patch.yaml
  target:
    kind: Secret
    name: secret