apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: prod-
namespace: production
images:
- name: gcr.io/go-portforio/search-item
  newTag: circle-ci
replicas:
- name: searchitem
  count: 1

resources:
- ../../../base/searchitem

patches:
- path: secret-patch.yaml
  target:
    kind: Secret
    name: searchitem-secret