apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: dev-
namespace: dev-mockten

images:
- name: gcr.io/go-portforio/mockten-notification
  newname: gcr.io/driven-rig-385015/notification
  newTag: manually
replicas:
- name: deploy
  count: 1

resources:
- ../../../base/notification