apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: statefulset
spec:
  serviceName: svc
  template:
    spec:
      containers:
        - image: mysql
          name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: common-secret
                  key: db_pass
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: dev-mockten-mysql-pvc
              mountPath: /var/lib/mysql
          resources:
            limits:
              cpu: 1000m
              memory: 1000m
            requests:
              cpu: 100m
              memory: 100m
      # affinity:
      #   nodeAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       nodeSelectorTerms:
      #       - matchExpressions:
      #         - key: topology.kubernetes.io/zone
      #           operator: In
      #           values:
      #           - us-east1-b