apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  template:
    spec:
      containers:
        # - image: docker.elastic.co/logstash/logstash:8.11.0
        - name: logstash
          resources:
            limits:
              cpu: 1000m
              memory: 1000m
            requests:
              cpu: 100m
              memory: 100m

