apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev-mockten
namePrefix: dev-

images:
replicas:
- name: deploy
  count: 1

resources:
- ../../../base/logstash

patches:
- path: deploy-patch.yaml
  target:
    group: apps
    version: v1
    kind: Deployment
    name: deploy
- path: secret-patch.yaml
  target:
    version: v1
    kind: Secret
    name: secret