apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  template:
    spec:
      volumes:
        - name: redis-persistent-storage
          gcePersistentDisk:
            pdName: dev-redis-disk
            fsType: ext4

