apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev-mockten
namePrefix: dev-
images:
- name: redis
  newTag: latest
replicas:
- name: statefulset
  count: 2

resources:
- ../../../base/redis

patches:
- path: stateful-patch.yaml
  target:
    group: apps
    version: v1
    kind: StatefulSet
    name: statefulset