apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev-mockten
namePrefix: dev-
images:
- name: redis
  newTag: "6.2"
replicas:
- name: statefulset
  count: 1

resources:
- ../../../base/redis
- redis-pv.yaml
- redis-pvc.yaml

patches:
- path: stateful-patch.yaml
  target:
    group: apps
    version: v1
    kind: StatefulSet
    name: statefulset