apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: dev-
namespace: dev-mockten

images:
- name: gcr.io/go-portforio/search-item
  newname: gcr.io/_GCP_PROJECT_ID_/searchitem
  newTag: v0.0.17
- name: getmeili/meilisearch
  newname: gcr.io/_GCP_PROJECT_ID_/meilisearch
  newTag: v0.0.2
replicas:
- name: statefulset
  count: 1

resources:
- ../../../base/searchitem
- search-pv.yaml
- search-pvc.yaml

patches:
- path: stateful-patch.yaml
  target:
    group: apps
    version: v1
    kind: StatefulSet
    name: statefulset
- path: secret-patch.yaml
  target:
    version: v1
    kind: Secret
    name: secret