apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: dev-
namespace: dev-mockten

images:
- name: gcr.io/go-portforio/search-item
  newname: gcr.io/_GCP_PROJECT_ID_/searchitem
  newTag: v0.0.11
- name: getmeili/meilisearch
  newname: gcr.io/_GCP_PROJECT_ID_/meilisearch
  newTag: v0.0.1
replicas:
- name: deploy
  count: 1

resources:
- ../../../base/searchitem