apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: dev-
namespace: dev-mockten

images:
- name: gcr.io/go-portforio/search-item
  newname: gcr.io/secret-node-394015/searchitem
  newTag: v0.0.1
replicas:
- name: deploy
  count: 1

resources:
- ../../../base/searchitem