apiVersion: v1
kind: PersistentVolume
metadata:
  name: search-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  gcePersistentDisk:
    pdName: dev-search-disk
    fsType: ext4