apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: statefulset
spec:
  serviceName: svc
  template:
    spec:
      containers:
        - image: mongodb
          name: mongodb
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo_init_username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo_init_password
          ports:
            - containerPort: 27017
              name: mongodb
          volumeMounts:
            - name: dev-mockten-mongo-pvc
              mountPath: /data/db
          resources:
            limits:
              cpu: 1000m
              memory: 1000m
            requests:
              cpu: 100m
              memory: 100m
      # affinity:
      #   nodeAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       nodeSelectorTerms:
      #       - matchExpressions:
      #         - key: topology.kubernetes.io/zone
      #           operator: In
      #           values:
      #           - us-east1-c