apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: grafana

namespace: mockten-observer

namePrefix: grafana-

generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
- name: grafana-config
  files:
  - config/grafana.ini
  
resources:
- grafana-deploy.yaml
- grafana-service.yaml
- grafana-ingress.yaml
- grafana-backendconfig.yaml