apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: prometheus

namespace: mockten-observer

namePrefix: prom-

generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
- name: prometheus-config
  files:
  - config/prometheus.yml
  
resources:
- prom-deploy.yaml
- prom-service.yaml
- prom-ingress.yaml
- prom-backendconfig.yaml
