apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: prod-
namespace: production
images:
- name: gcr.io/go-portforio/mockten-notification
  newTag: circle-ci
replicas:
- name: notification
  count: 1

resources:
- ../../../base/notification

patches:
- path: secret-patch.yaml
  target:
    kind: Secret
    name: notification-secret