name: deploy_to_gcp

on:
  push:
    branches:
      - main
      - initial
  pull_request:
    branches:
      - main
  workflow_dispatch: {}


jobs:
  dev_deploy:
    if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: kustomize/

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v1
    - name: GCP Authenticate
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}

    - name: Setup GCloud
      uses: 'google-github-actions/setup-gcloud@v1'
      with:
        version: '>= 363.0.0'

    - name: Configure docker to use the gcloud cli
      run: |
        gcloud components install gke-gcloud-auth-plugin && \
        gcloud container clusters get-credentials mockten-k8s-cluster --region us-east1 --project ${{ secrets.GCP_PROJECT_ID }}

    - name: rename secret value
      env: 
        SECRET_KEY_STRING: ${{ secrets.SECRET_KEY_STRING }}
        OPERATOR_ADDRESS: ${{ secrets.OPERATOR_ADDRESS }}
        SNS_API_KEY: ${{ secrets.SNS_API_KEY }}
        SNS_API_URL: ${{ secrets.SNS_API_URL }}
        MEILI_MASTERKEY: ${{ secrets.MEILI_MASTERKEY }}
      run: |
        echo "$SECRET_KEY_STRING" | cut -c 1-5 &&\
        echo "$OPERATOR_ADDRESS" | cut -c 1-5 &&\
        echo "$SNS_API_KEY" | cut -c 1-5 &&\
        echo "$SNS_API_URL" | cut -c 1-5 &&\
        sed -i "s/_SECRET_KEY_/"$SECRET_KEY_STRING"/g" base/ecpay/ecpay-secret.yaml &&\
        sed -i "s/_OPERATOR_ADDRESS_/"$OPERATOR_ADDRESS"/g" base/notification/nf-secret.yaml &&\
        sed -i "s/_SNS_API_KEY_/"$SNS_API_KEY"/g" base/notification/nf-secret.yaml &&\
        sed -i "s|_SNS_API_URL_|"$SNS_API_URL"|g" base/notification/nf-secret.yaml &&\
        sed -i "s/_MEILI_MASTERKEY_/"$MEILI_MASTERKEY"/g" overlays/dev/searchitem/secret-patch.yaml  &&\
        sed -i "s/_GCP_PROJECT_ID_/"${{ secrets.GCP_PROJECT_ID }}"/g" overlays/dev/adder/kustomization.yaml  &&\
        sed -i "s/_GCP_PROJECT_ID_/"${{ secrets.GCP_PROJECT_ID }}"/g" overlays/dev/ecfront/kustomization.yaml  &&\
        sed -i "s/_GCP_PROJECT_ID_/"${{ secrets.GCP_PROJECT_ID }}"/g" overlays/dev/ecpay/kustomization.yaml  &&\
        sed -i "s/_GCP_PROJECT_ID_/"${{ secrets.GCP_PROJECT_ID }}"/g" overlays/dev/notification/kustomization.yaml  &&\
        sed -i "s/_GCP_PROJECT_ID_/"${{ secrets.GCP_PROJECT_ID }}"/g" overlays/dev/payexecution/kustomization.yaml  &&\
        sed -i "s/_GCP_PROJECT_ID_/"${{ secrets.GCP_PROJECT_ID }}"/g" overlays/dev/ranking/kustomization.yaml  &&\
        sed -i "s/_GCP_PROJECT_ID_/"${{ secrets.GCP_PROJECT_ID }}"/g" overlays/dev/mongodb/kustomization.yaml  &&\
        sed -i "s/_GCP_PROJECT_ID_/"${{ secrets.GCP_PROJECT_ID }}"/g" overlays/dev/searchitem/kustomization.yaml &&\
        sed -i "s/_GCP_PROJECT_ID_/"${{ secrets.GCP_PROJECT_ID }}"/g" overlays/dev/init-job/kustomization.yaml

    - name: deploy
      run: kubectl apply -k overlays/dev/
