apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: searchitem

namePrefix: searchitem-

configMapGenerator:
- name: meili-config
  files:
  - config/config.toml

resources:
- searchitem-statefulset.yaml
- searchitem-service.yaml
- searchitem-secret.yaml