apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: searchitem

namePrefix: searchitem-

resources:
- searchitem-deploy.yaml
- searchitem-secret.yaml
- searchitem-service.yaml

