apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: StatefulSet
metadata:
  name: statefulset
spec:
  selector:
    matchLabels:
      app: searchitem
  serviceName: svc
  template:
    metadata:
      labels:
        app: searchitem
    spec:
      containers:
      - name: searchitem
        image: mockten/searchitem
        ports:
        - containerPort: 50051
          name: apl
        - containerPort: 9100
          name: metrics
        command: ["./searchitem"]
        resources:
          limits:
            cpu: 500m
            memory: 500m
          requests:
            cpu: 100m
            memory: 100m
        volumeMounts:
        - name: dev-mockten-search-pvc
          mountPath: /data/index