apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: StatefulSet
metadata:
  name: statefulset
spec:
  selector:
    matchLabels:
      app: searchitem
  serviceName: svc
  template:
    metadata:
      labels:
        app: searchitem
    spec:
      containers:
      - name: searchitem-app
        image: gcr.io/go-portforio/search-item
        ports:
        - containerPort: 50051
          name: apl
        - containerPort: 9100
          name: prometheus
        command: ["./searchitem"]
        env:
        - name: MEILISEARCH_MASTERKEY
          valueFrom:
            secretKeyRef:
              name: searchitem-secret
              key: masterkey
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: searchitem-secret
              key: mongo_init_username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: searchitem-secret
              key: mongo_init_password
        resources:
          limits:
            cpu: 500m
            memory: 500m
          requests:
            cpu: 100m
            memory: 100m